jms_security_extra:
    secure_all_services: false
    expressions: true
    voters:
        disable_acl: true

security:
    encoders:
       # Symfony\Component\Security\Core\User\User: plaintext
        fibe\SecurityBundle\Entity\User:
         # id : fos_user.password_provider.encoder
          algorithm: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    acl:
        connection: default

    access_decision_manager:
        # La valeur de « Strategy » peut être : affirmative, unanimous ou consensus
        strategy: affirmative

#        in_memory:
#            memory:
#                users:
#                    #define here the user password of the "admin" account
#                    admin: { password: wwwconfTER, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   /login$
            anonymous: true # On autorise les anonymes sur ce pare-feu

        oauth_login:
            pattern:   ^/connect
            anonymous: true # On autorise les anonymes sur ce pare-feu

        main:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
#               login_path: fos_user_security_login
#               check_path: fos_user_security_check
                login_path: /login
                check_path: /login/login_check
                default_target_path: dashboard_index
                success_handler: authentication_handler
                failure_handler: authentication_handler
                require_previous_session: false # The default value is true
                #
              #  success_handler: fibe_security.select_conference_success_handler
            oauth:
                resource_owners:
                    google:         "/login/check-google"
                    twitter:        "/login/check-twitter"
                    facebook:       "/login/check-facebook"
                    linkedin:       "/login/check-linkedin"
                login_path:        /login
                failure_path:      /login
                default_target_path: /
                use_forward:       false
                success_handler: authentication_handler
                failure_handler: authentication_handler
                # use_forward:       true

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:
                path:   logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

